# Generated by Django 6.0 on 2026-02-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('ilahiyat', 'İlahiyat'), ('isg', 'İş Sağlığı Ve Güvenliği'), ('beslenmevediyetetik', 'Beslenme Ve Diyetetik'), ('hemsirelik', 'Hemşirelik'), ('saglikkurumlarıisletmeciligi', 'Sağlık Kurumları İşletmeciliği'), ('webtasarimvekodlama', 'Web Tasarım Ve Kodlama')], max_length=50, null=True, verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Toplam Puan'),
        ),
    ]
