# Generated by Django 6.0 on 2026-03-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_user_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('cocukgelisimi', 'Çocuk Gelişimi'), ('diyaliz', 'Diyaliz'), ('disprotezteknolojisi', 'Diş Protez Teknolojisi'), ('eczanehizmetleri', 'Eczane Hizmetleri'), ('fizyoterapi', 'Fizyoterapi')], max_length=50, null=True, verbose_name='Bölüm'),
        ),
    ]
