# Generated by Django 6.0 on 2026-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('cocukgelisimi', 'Çocuk Gelişimi'), ('diyaliz', 'Diyaliz'), ('disprotezteknolojisi', 'Diş Protez Teknolojisi'), ('eczanehizmetleri', 'Eczane Hizmetleri'), ('fizyoterapi', 'Fizyoterapi')], db_index=True, max_length=50, null=True, verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Öğrenci mi?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Akademisyen mi?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Toplam Puan'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'is_student'], name='users_user_departm_92cad3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_student', '-total_points'], name='users_user_is_stud_0f89ed_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'is_student', '-total_points'], name='users_user_departm_3bf0e3_idx'),
        ),
    ]
