# Generated by Django 6.0 on 2026-10-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emailotp_created_at_alter_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Kategori'),
        ),
    ]
