# Generated by Django 6.0 on 2026-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('siyasetbilimi', 'Siyaset Bilimi ve Kamu Yönetimi'), ('turkdili', 'Türk Dili ve Edebiyatı'), ('matematik', 'Matematik'), ('sb', 'Siyaset Bilimi ve Kamu Yönetimi'), ('td', 'Türk Dili ve Edebiyatı'), ('mt', 'Matematik')], db_index=True, max_length=50, null=True, verbose_name='Bölüm'),
        ),
    ]
