# Generated by Django 6.0 on 2026-10-07 20:15

from django.db import migrations, models

def migrate_old_departments(apps, schema_editor):
    User = apps.get_model('users', 'User')
    # Single UPDATE call to prevent Oracle parallel transaction lock
    User.objects.exclude(department__in=['siyasetbilimi', 'turkdili', 'matematik', '']).update(department='siyasetbilimi')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_department'),
    ]

    operations = [
        migrations.RunPython(migrate_old_departments, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(
                blank=True, 
                choices=[
                    ('siyasetbilimi', 'Siyaset Bilimi ve Kamu Yönetimi'), 
                    ('turkdili', 'Türk Dili ve Edebiyatı'), 
                    ('matematik', 'Matematik')
                ], 
                db_index=True, 
                max_length=50, 
                null=True, 
                verbose_name='Bölüm'
            ),
        ),
    ]
