# Generated by Django 6.0 on 2025-12-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(unique=True, verbose_name='Hafta')),
                ('title', models.CharField(max_length=200, verbose_name='Hafta Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Ders Notları')),
            ],
            options={
                'verbose_name': 'Haftalık İçerik',
                'verbose_name_plural': 'Haftalık İçerikler',
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('podcast', 'Podcast'), ('form', 'Google Form')], max_length=10)),
                ('embed_url', models.URLField(verbose_name='Materyal Linki (YouTube/Form Embed URL)')),
                ('title', models.CharField(max_length=200, verbose_name='Materyal Başlığı')),
                ('parent_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='contents.weeklycontent')),
            ],
        ),
    ]
