# Generated by Django 6.0 on 2026-01-12 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='embed_url',
            field=models.URLField(verbose_name='Materyal Linki'),
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weekly_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.weeklycontent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weekly_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.weeklycontent')),
            ],
            options={
                'verbose_name': 'Öğrenci İlerlemesi',
                'verbose_name_plural': 'Öğrenci İlerlemeleri',
                'unique_together': {('student', 'weekly_content')},
            },
        ),
    ]
