# Generated by Django 6.0 on 2026-01-23 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycontent',
            name='intro_title',
            field=models.CharField(default='Haftaya Giriş', max_length=255, verbose_name='Tanıtım Başlığı'),
        ),
        migrations.AddField(
            model_name='weeklycontent',
            name='intro_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Tanıtım Videosu (Embed Link)'),
        ),
        migrations.CreateModel(
            name='IntroVideoCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weekly_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_intros', to='contents.weeklycontent')),
            ],
            options={
                'verbose_name': 'Tanıtım Videosu Tamamlama',
                'verbose_name_plural': 'Tanıtım Videosu Tamamlamaları',
                'unique_together': {('student', 'weekly_content')},
            },
        ),
    ]
