# Generated by Django 6.0 on 2026-01-23 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_weeklycontent_intro_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introvideocompletion',
            options={'verbose_name': 'Genel Tanıtım Tamamlama', 'verbose_name_plural': 'Genel Tanıtım Tamamlamaları'},
        ),
        migrations.AlterUniqueTogether(
            name='introvideocompletion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='weeklycontent',
            name='intro_title',
        ),
        migrations.RemoveField(
            model_name='weeklycontent',
            name='intro_video_url',
        ),
        migrations.AlterField(
            model_name='introvideocompletion',
            name='is_watched',
            field=models.BooleanField(default=False, verbose_name='İzledi mi?'),
        ),
        migrations.AlterField(
            model_name='introvideocompletion',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intro_status', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci'),
        ),
        migrations.AlterField(
            model_name='introvideocompletion',
            name='watched_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='İzleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('podcast', 'Podcast'), ('form', 'Bilgi Testi')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='introvideocompletion',
            name='weekly_content',
        ),
    ]
