# Generated by Django 6.0 on 2026-01-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_introvideocompletion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycontent',
            name='intro_title',
            field=models.CharField(default='Genel Tanıtım', max_length=255, verbose_name='Tanıtım Başlığı'),
        ),
        migrations.AddField(
            model_name='weeklycontent',
            name='intro_video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Tanıtım Videosu (Embed Link)'),
        ),
    ]
