# Generated by Django 6.0 on 2026-01-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_weeklycontent_intro_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycontent',
            name='release_date',
            field=models.DateTimeField(blank=True, help_text='Bu tarih gelmeden öğrenci içeriğe erişemez.', null=True, verbose_name='Erişime Açılma Tarihi'),
        ),
    ]
