# Generated by Django 6.0 on 2026-01-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_quiz_quizquestion_quizoption_studentquizattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('weekly_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='contents.weeklycontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
