# Generated by Django 6.0 on 2026-02-14 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_weeklycontent_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['order'], 'verbose_name': 'Haftalık Kaynak', 'verbose_name_plural': 'Haftalık Kaynaklar'},
        ),
        migrations.AlterUniqueTogether(
            name='completedmaterial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='completedmaterial',
            name='attempt_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='material',
            name='point_value',
            field=models.PositiveIntegerField(default=1, verbose_name='Tamamlama Puanı'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='current_attempt_round',
            field=models.PositiveIntegerField(default=1, verbose_name='Aktif Deneme Turu'),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='attempt_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='attempt_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.material'),
        ),
        migrations.AddField(
            model_name='weeklycontent',
            name='intro_description',
            field=models.TextField(blank=True, null=True, verbose_name='Tanıtım Metni/Açıklaması'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(verbose_name='OneDrive Linki'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(verbose_name='Kaynak Başlığı'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('podcast', 'Podcast'), ('form', 'Bilgi Testi'), ('pdf', 'Ders Notu (PDF)'), ('assignment', 'Ödev (Microsoft Form)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='embed_url',
            field=models.URLField(help_text='Video/Podcast embed kodu veya OneDrive PDF indirme linki.', verbose_name='Materyal Linki'),
        ),
        migrations.AlterUniqueTogether(
            name='completedmaterial',
            unique_together={('student', 'material', 'attempt_round')},
        ),
    ]
