# Generated by Django 6.0 on 2026-03-27 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_alter_flashcard_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Soru Metni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ön Test Sorusu',
                'verbose_name_plural': 'Ön Test Soruları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PreTestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, verbose_name='Seçenek Metni')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Doğru Şık mı?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='contents.pretestquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PreTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Doğru Sayısı')),
                ('wrong_answers', models.IntegerField(default=0, verbose_name='Yanlış Sayısı')),
                ('score', models.FloatField(default=0.0, verbose_name='Başarı Puanı')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Tamamlanma Tarihi')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_test_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ön Test Sonucu',
                'verbose_name_plural': 'Ön Test Sonuçları',
            },
        ),
    ]
