# Generated by Django 6.0 on 2026-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_pretestquestion_pretestoption_pretestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Öğrenci bu soruyu yanlış yaptığında gösterilecek hazır yapay zeka veya hoca analizi.', null=True, verbose_name='Soru Analizi / Açıklaması'),
        ),
    ]
