# Generated by Django 6.0 on 2026-04-08 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_quizquestion_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPreTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Soru Metni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('appearing_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_questions', to='contents.weeklycontent', verbose_name='Hangi Haftanın Girişinde Sorulacak?')),
                ('target_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by_questions', to='contents.weeklycontent', verbose_name='Hangi Haftanın Konusu? (Yanlışta Açılacak Hafta)')),
            ],
            options={
                'verbose_name': 'Haftalık Hazırlık Sorusu',
                'verbose_name_plural': 'Haftalık Hazırlık Soruları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPreTestOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, verbose_name='Seçenek Metni')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Doğru mu?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='contents.weeklypretestquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_until', models.DateTimeField(verbose_name='Kilit Ne Zamana Kadar Açık?')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_unlocks', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.weeklycontent')),
            ],
            options={
                'verbose_name': 'Geçici Kilit Açma',
                'verbose_name_plural': 'Geçici Kilit Açmaları',
                'unique_together': {('student', 'week')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyPreTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.weeklycontent')),
            ],
            options={
                'unique_together': {('student', 'week')},
            },
        ),
    ]
