# Generated by Django 6.0 on 2026-04-10 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_weeklypretestquestion_weeklypretestoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Eski tabloyu sildiğimiz için AddField yerine CreateModel kullanıyoruz.
        # Bu sayede Oracle "compressed table" hatası vermez.
        migrations.CreateModel(
            name='WeeklyPreTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('unlocked_weeks_json', models.JSONField(blank=True, default=list)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_pretest_results', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.weeklycontent')),
            ],
            options={
                'verbose_name': 'Haftalık Giriş Test Sonucu',
                'verbose_name_plural': 'Haftalık Giriş Test Sonuçları',
                'unique_together': {('student', 'week')},
            },
        ),
    ]
