# Generated by Django 6.0 on 2026-04-20 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_alter_weeklypretestresult_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rozet Adı')),
                ('description', models.TextField(verbose_name='Rozet Açıklaması')),
                ('icon_name', models.CharField(help_text='Lucide ikon adı (örn: Zap, Trophy, Star)', max_length=50)),
                ('color', models.CharField(default='#FACC15', help_text='Tailwind rengi veya HEX kodu', max_length=20)),
                ('badge_type', models.CharField(choices=[('first_material', 'İlk Materyal Tamamlama'), ('double_test_streak', '2 Hafta Üst Üste Başarı'), ('manual', 'Manuel (Hoca Tarafından Verilen)')], default='manual', max_length=30)),
                ('requirement_text', models.CharField(help_text='Örn: 2 hafta üst üste testi tamamla', max_length=255, verbose_name='Gereksinim Metni')),
            ],
            options={
                'verbose_name': 'Rozet Tanımı',
                'verbose_name_plural': 'Rozet Tanımları',
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Öğrenci Rozeti',
                'verbose_name_plural': 'Öğrenci Rozetleri',
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
