# Generated by Django 6.0 on 2026-04-24 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_survey_surveyquestion_studentsurveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, verbose_name='Seçenek Metni')),
                ('value', models.IntegerField(verbose_name='Puan Değeri')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='contents.surveyquestion')),
            ],
        ),
    ]
