# Generated by Django 6.0 on 2026-04-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_surveyoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsurveyresponse',
            name='answer_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seçilen Şık Metni'),
        ),
    ]
