# Generated by Django 6.0 on 2026-08-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_studentsurveyresponse_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycontent',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Bu tarih geçtikten sonra öğrenci içeriğe erişemez.', null=True, verbose_name='Erişime Kapanma (Pasif Olma) Tarihi'),
        ),
    ]
