# Generated by Django 6.0 on 2026-08-09 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_alter_weeklycontent_optional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyContentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='Bölüm Kodu')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Erişime Açılma Tarihi')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Erişime Kapanma (Pasif Olma) Tarihi')),
                ('weekly_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='contents.weeklycontent', verbose_name='Haftalık İçerik')),
            ],
            options={
                'verbose_name': 'Bölüm Bazlı Hafta Takvimi',
                'verbose_name_plural': 'Bölüm Bazlı Hafta Takvimleri',
                'unique_together': {('weekly_content', 'department')},
            },
        ),
    ]
