# Generated by Django 6.0 on 2026-08-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0018_weeklycontentschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='min_duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=300, null=True, verbose_name='Minimum İzleme/Dinleme Süresi (Saniye)'),
        ),
    ]
