# Generated by Django 6.0 on 2026-08-19 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0019_material_min_duration_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetracking',
            options={'verbose_name': 'Zaman Takibi', 'verbose_name_plural': 'Zaman Takipleri'},
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['student', 'weekly_content', 'material', 'attempt_round', 'date'], name='contents_ti_student_5f7c97_idx'),
        ),
    ]
