# Generated by Django 6.0 on 2026-08-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0020_alter_timetracking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='predicted_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Tahmin Edilen Puan'),
        ),
    ]
