# Generated by Django 6.0 on 2026-08-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0021_studentquizattempt_predicted_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, verbose_name='Bölüm Kodu')),
                ('week_number', models.IntegerField(verbose_name='Raporlanan Hafta')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('recipients', models.TextField(verbose_name='Alıcı E-postalar')),
                ('student_count', models.IntegerField(default=0, verbose_name='Raporlanan Öğrenci Sayısı')),
                ('status', models.CharField(default='SUCCESS', max_length=20, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
            ],
            options={
                'verbose_name': 'Akademisyen E-posta Rapor Günlüğü',
                'verbose_name_plural': 'Akademisyen E-posta Rapor Günlükleri',
                'ordering': ['-sent_at'],
                'unique_together': {('department', 'week_number')},
            },
        ),
    ]
