# Generated by Django 6.0 on 2026-09-10 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0022_academicemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='ai_response_text',
            field=models.TextField(blank=True, null=True, verbose_name='Yapay Zeka Yanıtı'),
        ),
        migrations.AlterField(
            model_name='studentquestion',
            name='weekly_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.weeklycontent'),
        ),
    ]
