# Generated by Django 6.0 on 2026-09-12 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0023_studentquestion_ai_response_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicemaillog',
            name='department',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Bölüm Kodu'),
        ),
        migrations.AlterField(
            model_name='academicemaillog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Gönderilme Tarihi'),
        ),
        migrations.AlterField(
            model_name='academicemaillog',
            name='status',
            field=models.CharField(db_index=True, default='SUCCESS', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='academicemaillog',
            name='week_number',
            field=models.IntegerField(db_index=True, verbose_name='Raporlanan Hafta'),
        ),
        migrations.AlterField(
            model_name='completedmaterial',
            name='attempt_round',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='completedmaterial',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='introvideocompletion',
            name='is_watched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='İzledi mi?'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('podcast', 'Podcast'), ('form', 'Bilgi Testi'), ('pdf', 'Ders Notu (PDF)'), ('assignment', 'Ödev (Microsoft Form)')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pretestoption',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Doğru Şık mı?'),
        ),
        migrations.AlterField(
            model_name='pretestresult',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Tamamlandı mı?'),
        ),
        migrations.AlterField(
            model_name='quizoption',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='studentbadge',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='current_attempt_round',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Aktif Deneme Turu'),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='studentquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='attempt_round',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='score',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='studentsurveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='temporaryunlock',
            name='unlock_until',
            field=models.DateTimeField(db_index=True, verbose_name='Kilit Ne Zamana Kadar Açık?'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='attempt_round',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='weeklycontent',
            name='due_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Bu tarih geçtikten sonra öğrenci içeriğe erişemez.', null=True, verbose_name='Erişime Kapanma (Pasif Olma) Tarihi'),
        ),
        migrations.AlterField(
            model_name='weeklycontent',
            name='release_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Bu tarih gelmeden öğrenci içeriğe erişemez.', null=True, verbose_name='Erişime Açılma Tarihi'),
        ),
        migrations.AlterField(
            model_name='weeklycontentschedule',
            name='department',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Bölüm Kodu'),
        ),
        migrations.AlterField(
            model_name='weeklypretestoption',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Doğru mu?'),
        ),
        migrations.AlterField(
            model_name='weeklypretestquestion',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='weeklypretestresult',
            name='is_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='academicemaillog',
            index=models.Index(fields=['department', '-sent_at'], name='contents_ac_departm_09d18e_idx'),
        ),
        migrations.AddIndex(
            model_name='completedmaterial',
            index=models.Index(fields=['student', 'attempt_round'], name='contents_co_student_bdacad_idx'),
        ),
        migrations.AddIndex(
            model_name='completedmaterial',
            index=models.Index(fields=['material', 'attempt_round'], name='contents_co_materia_328bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='introvideocompletion',
            index=models.Index(fields=['student', 'is_watched'], name='contents_in_student_e45071_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['parent_content', 'content_type'], name='contents_ma_parent__a862a0_idx'),
        ),
        migrations.AddIndex(
            model_name='pretestresult',
            index=models.Index(fields=['student', 'is_completed'], name='contents_pr_student_8bb4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='quizoption',
            index=models.Index(fields=['question', 'is_correct'], name='contents_qu_questio_0415e4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='contents_st_attempt_16d03f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['question', 'is_correct'], name='contents_st_questio_535828_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbadge',
            index=models.Index(fields=['student', 'earned_at'], name='contents_st_student_cedfbb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'is_completed'], name='contents_st_student_4c5123_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['weekly_content', 'is_completed'], name='contents_st_weekly__85d59d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'current_attempt_round'], name='contents_st_student_e85868_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'weekly_content', 'is_completed'], name='contents_st_student_b9d75c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquestion',
            index=models.Index(fields=['student', 'weekly_content'], name='contents_st_student_eb755e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquestion',
            index=models.Index(fields=['student', '-created_at'], name='contents_st_student_af2051_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquestion',
            index=models.Index(fields=['student', 'weekly_content', '-created_at'], name='contents_st_student_eea5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['student', 'quiz'], name='contents_st_student_4efcc5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['student', 'attempt_round'], name='contents_st_student_bb63d9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['quiz', 'attempt_round'], name='contents_st_quiz_id_1c112d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['student', 'quiz', 'attempt_round'], name='contents_st_student_c4bc95_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['-completed_at'], name='contents_st_complet_eccb67_idx'),
        ),
        migrations.AddIndex(
            model_name='temporaryunlock',
            index=models.Index(fields=['student', 'unlock_until'], name='contents_te_student_07bc72_idx'),
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['student', 'attempt_round'], name='contents_ti_student_15c266_idx'),
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['weekly_content', 'attempt_round'], name='contents_ti_weekly__9e7b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['student', 'material', 'attempt_round'], name='contents_ti_student_e6e243_idx'),
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['date'], name='contents_ti_date_ecda42_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklycontent',
            index=models.Index(fields=['release_date', 'due_date'], name='contents_we_release_3ad705_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklypretestresult',
            index=models.Index(fields=['student', 'is_completed'], name='contents_we_student_feef0a_idx'),
        ),
    ]
